// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Firebase options are not configured for Linux.',
        );
      default:
        throw UnsupportedError('Firebase is not supported on this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3aDoFUfMSCLk-LLonUd49NCL8kGfU6jU',
    appId: '1:885732918471:web:2413476198f8681f82eae2',
    messagingSenderId: '885732918471',
    projectId: 'campus-notify-cc71e',
    authDomain: 'campus-notify-cc71e.firebaseapp.com',
    storageBucket: 'campus-notify-cc71e.firebasestorage.app',
    measurementId: 'G-WEJPDQ6DZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASGlRoA4bxiNNPXmT8uPr8gYjI20BnBus',
    appId: '1:885732918471:android:eeda75db8398fded82eae2',
    messagingSenderId: '885732918471',
    projectId: 'campus-notify-cc71e',
    storageBucket: 'campus-notify-cc71e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiDo9j652QaB_PMXN6RXrwwDBvvWrdMwM',
    appId: '1:885732918471:ios:11cac9340188230282eae2',
    messagingSenderId: '885732918471',
    projectId: 'campus-notify-cc71e',
    storageBucket: 'campus-notify-cc71e.firebasestorage.app',
    iosBundleId: 'com.example.campusNotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiDo9j652QaB_PMXN6RXrwwDBvvWrdMwM',
    appId: '1:885732918471:ios:11cac9340188230282eae2',
    messagingSenderId: '885732918471',
    projectId: 'campus-notify-cc71e',
    storageBucket: 'campus-notify-cc71e.firebasestorage.app',
    iosBundleId: 'com.example.campusNotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3aDoFUfMSCLk-LLonUd49NCL8kGfU6jU',
    appId: '1:885732918471:web:1be836c472bb34be82eae2',
    messagingSenderId: '885732918471',
    projectId: 'campus-notify-cc71e',
    authDomain: 'campus-notify-cc71e.firebaseapp.com',
    storageBucket: 'campus-notify-cc71e.firebasestorage.app',
    measurementId: 'G-QHR713W7SH',
  );
}
